config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  devise_for :penggunas
  resources :tulisans do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :pengguna
  belongs_to :tulisan
end

app/models/pengguna.rb
class Pengguna < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tulisans
  has_many :comments
end

app/models/tulisan.rb
class Tulisan < ApplicationRecord
  paginates_per 10
  belongs_to :pengguna
  has_many :comments 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @tulisan = Tulisan.find(params[:tulisan_id])
    @comment = @tulisan.comments.create(params[:comment].permit(:comment))
    @comment.pengguna_id = current_pengguna.id if current_pengguna
    @comment.save

    if @comment.save
      redirect_to tulisan_path(@tulisan)
    else
      render 'new'
    end
  end

  def destroy
    @tulisan = Tulisan.find(params[:tulisan_id])
    @comment = @tulisan.comments.find(params[:id])
    @comment.destroy
    redirect_to tulisan_path(@tulisan)
  end

  def edit
    @tulisan = Tulisan.find(params[:tulisan_id])
    @comment = @tulisan.comments.find(params[:id])
  end

  def update
    @tulisan = Tulisan.find(params[:comment].permit(:comment))
    @comment = @tulisan.comments.find(params[:id])
    if @comment.update(params[:comment].permit(:comment))
      redirect_to tulisan_path(@tulisan)
    else
      render 'edit'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/tulisans_controller.rb
class TulisansController < ApplicationController
  before_action :set_tulisan, only: [:show, :edit, :update, :destroy]

  # GET /tulisans
  # GET /tulisans.json
  def index
    @tulisans = Tulisan.order(:judul).page params[:page]
    #= User.order(:name).page params[:page]
  end

  # GET /tulisans/1
  # GET /tulisans/1.json
  def show
  end

  # GET /tulisans/new
  def new
    @tulisan = current_pengguna.tulisans.build
  end

  # GET /tulisans/1/edit
  def edit
  end

  # POST /tulisans
  # POST /tulisans.json
  def create
    @tulisan = current_pengguna.tulisans.build(tulisan_params)

    respond_to do |format|
      if @tulisan.save
        format.html { redirect_to @tulisan, notice: 'Tulisan was successfully created.' }
        format.json { render :show, status: :created, location: @tulisan }
      else
        format.html { render :new }
        format.json { render json: @tulisan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tulisans/1
  # PATCH/PUT /tulisans/1.json
  def update
    respond_to do |format|
      if @tulisan.update(tulisan_params)
        format.html { redirect_to @tulisan, notice: 'Tulisan was successfully updated.' }
        format.json { render :show, status: :ok, location: @tulisan }
      else
        format.html { render :edit }
        format.json { render json: @tulisan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tulisans/1
  # DELETE /tulisans/1.json
  def destroy
    @tulisan.destroy
    respond_to do |format|
      format.html { redirect_to tulisans_url, notice: 'Tulisan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tulisan
      @tulisan = Tulisan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tulisan_params
      params.require(:tulisan).permit(:judul, :isi, :penulis)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tulisans_helper.rb
module TulisansHelper
end

app/views/comments/_comment.html.erb
<br>
<div class="card is-horizontal">
  <div class=" card-header" style="font-weight: 0;align-text: center;padding: 0.75rem;display: flex;">
    <h3>balasan dari : <b> <%= comment.pengguna.email %></b>, pada <%= time_ago_in_words(@tulisan.created_at) %></h3>
  </div>
  <div class="card-content">
    <%= comment.comment  %>
  </div>
  <div class="card-footer">
    <%= link_to "Hapus", [comment.tulisan, comment], method: :delete,class: "button is-danger is-rounded" ,data: { confirm: "Kamu Yakin ? UwU" } %>
    <%= link_to "Ubah", edit_tulisan_comment_path(comment.tulisan,comment), class: "button is-warning is-rounded" %>
  </div>
</div>
<br>

app/views/comments/_form.html.erb
<div class="card card-content">
  <%= simple_form_for([@tulisan, @tulisan.comments.build]) do |f| %>
    <%= f.input :comment,class: "input" %>
    <%= f.submit :balas,class: "button is-primary" %>
  <% end %>
</div>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>K</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!--
    Dikembangkan oleh : Rachellia Agata 
  -->
    <nav class="navbar is-fixed-top">
      <div class="container is-small">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <img src="/logos/ftw/ftw_mark_white.png" alt="KCSI Brand">
            <span class="is-size-7 has-text-weight-light">&nbsp;&nbsp;Kelaurga Komputer Science</span>
          </a>
          <div id="navbar-toggle" role="button" tabindex="0" class="navbar-burger burger">
            <span>
            </span>
            <span>
            </span>
            <span>
            </span>
          </div>
        </div>
        <div class="navbar-menu">
          <div class="navbar-end">
            <a class="navbar-item" href="/penggunas/sign_in"> Sign in</a>
            <a class="navbar-item" href="/penggunas/sign_up"> Sign ip</a>
          </div>
        </div>
      </div>
    </nav>
    <br>
    <br> 
    <div class="container is-fluid" style="padding: 1.5rem;">
      <%= yield %>
    </div>
        <script type="text/javascript">
        document.getElementById("navbar-toggle").addEventListener ("click", toggleNav);
        function toggleNav() {
                var nav = document.getElementById("navbar-menu");
                var className = nav.getAttribute("class");
                if(className == "navbar-right navbar-menu") {
                    nav.className = "navbar-right navbar-menu is-active";
                } else {
                    nav.className = "navbar-right navbar-menu";
                }
        }
    </script>
  </body>
</html>

app/views/tulisans/_form.html.erb
<%= form_with(model: tulisan, local: true) do |form| %>
  <% if tulisan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tulisan.errors.count, "error") %> prohibited this tulisan from being saved:</h2>

      <ul>
      <% tulisan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :judul %>
    <%= form.text_area :judul %>
  </div>

  <div class="field">
    <%= form.label :isi %>
    <%= form.text_area :isi %>
  </div>

  <div class="field">
    <%= form.label :penulis %>
    <%= form.text_area :penulis %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tulisans/edit.html.erb
<h1>Editing Tulisan</h1>

<%= render 'form', tulisan: @tulisan %>

<%= link_to 'Show', @tulisan %> |
<%= link_to 'Back', tulisans_path %>

app/views/tulisans/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Tulisan</h1>
<%= link_to 'Tambah Tulisan', new_tulisan_path,class: "button is-primary is-rounded is-right" %>
<hr>
    <% @tulisans.each do |tulisan| %>
      <div class="box article">
        <div class="media-content">
          <div class="media-right">
            <%= link_to tulisan.judul, tulisan,class: "disable is-light is-rounded title"  %>
            <h3 class="is-size-6">Opening Post : <%= tulisan.pengguna.email %></h3>
            <hr>
          </div>
         <div class="">
          <div class="columns is-variable is-2-mobile is-2-tablet is-3-desktop is-8-widescreen is-2-fullhd">
          </div>
        </div>
        </div>
      </div>
    <% end %>
<br>

<%= paginate @tulisans %>

app/views/tulisans/new.html.erb
<h1>New Tulisan</h1>

<%= render 'form', tulisan: @tulisan %>

<%= link_to 'Back', tulisans_path %>

app/views/tulisans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1 class="title"><%= @tulisan.judul %></h1>
  <h3> Trit dipublis oleh :   <b>  <%= @tulisan.penulis %></b>, pada <%= time_ago_in_words @tulisan.created_at %></h3>
</p>
<hr>
<div class="card is-rounded">
  <header class="card-header">
    <h3 class="" style="font-weight: 0;align-text: center;padding: 0.75rem;display: flex;">
    dipublis oleh :   <b>  <%= @tulisan.penulis %></b>, pada <%= time_ago_in_words @tulisan.updated_at %>
    </h3>
    <div href="#" class="card-header-icon" aria-label="more options" style="padding: 0.75rem;display: flex">
      <span class="icon">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
     </span>
    </div>
  </header>
  <div class="card-content">
    <div class="content">
      <%= @tulisan.isi %>
      <br>
    </div>
  </div>
  <footer class="card-footer">
          <%= link_to 'Edit', edit_tulisan_path(@tulisan),class: "button is-warning is-rounded card-footer-item"%>
          <%= link_to 'Hapus', @tulisan, method: :delete, data: { confirm: 'Are you sure?' },class: "button is-rounded is-danger card-footer-item" %>
 
  </footer>
</div>
<div>
</div>

<%= render @tulisan.comments %>

<%= render "comments/form" %>

<%= link_to 'Back', tulisans_path %>